name: Dump Pixel Configs

on:
  workflow_dispatch:

jobs:
  dump:
    runs-on: ubuntu-latest

    steps:
      - name: Download source
        run: |
          wget -O kernel.tar.xz \
            https://github.com/yapixel/gki-build-assets/releases/download/pantah-15260412/kernel-pantah-15260412.tar.xz

      - name: Extract source
        run: |
          tar -xJf kernel.tar.xz

      - name: Dump build configs
        run: |
          cd kernel-pantah-15260412

          mkdir -p dump

          echo "===== build.config.gs201 =====" \
            > dump/build_config_gs201.txt

          cat private/devices/google/gs201/build.config.gs201 \
            >> dump/build_config_gs201.txt

          echo "===== build.config.pantah =====" \
            > dump/build_config_pantah.txt

          cat private/devices/google/pantah/build.config.pantah \
            >> dump/build_config_pantah.txt

      - name: Dump defconfigs
        run: |
          cd kernel-pantah-15260412

          mkdir -p dump

          cat private/devices/google/gs201/gs201_defconfig \
            > dump/gs201_defconfig.txt

          cat private/devices/google/pantah/pantah_defconfig \
            > dump/pantah_defconfig.txt

      - name: Upload files
        uses: actions/upload-artifact@v4
        with:
          name: pixel-configs
          path: |
            kernel-pantah-15260412/dump/build_config_gs201.txt
            kernel-pantah-15260412/dump/build_config_pantah.txt
            kernel-pantah-15260412/dump/gs201_defconfig.txt
            kernel-pantah-15260412/dump/pantah_defconfig.txt
